"""Add gallery photos table

Revision ID: 28b30572af72
Revises: e854891619aa
Create Date: 2026-09-05 21:46:58.751514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b30572af72'
down_revision = 'e854891619aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('privacy_level', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_photos_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_photos_uploaded_by'))

    op.drop_table('gallery_photos')
    # ### end Alembic commands ###
