"""Add events table

Revision ID: 78429a8b9eab
Revises: 43e3d1d9bf74
Create Date: 2026-09-05 21:29:51.927125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78429a8b9eab'
down_revision = '43e3d1d9bf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('privacy_level', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_created_by'))

    op.drop_table('events')
    # ### end Alembic commands ###
