"""Create family members table

Revision ID: 9ff744edf59e
Revises: 4d73417931ae
Create Date: 2026-09-04 10:11:38.078221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff744edf59e'
down_revision = '4d73417931ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('permanent_address', sa.String(length=255), nullable=True),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_members')
    # ### end Alembic commands ###
