"""Add family history table

Revision ID: cffeb712511d
Revises: e8bc58b7c8c2
Create Date: 2026-09-06 06:22:56.227995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffeb712511d'
down_revision = 'e8bc58b7c8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('privacy_level', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_history_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_history_created_by'))

    op.drop_table('family_history')
    # ### end Alembic commands ###
